<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{0ce4d6ef-3580-40cb-80fe-c304716bd060}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[StateProgram();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="39" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>